const { Show } = require('../server/db');

module.exports = {
  fmab: {
    title: 'Fullmetal Alchemist: Brotherhood',
    isFav: true,
    rating: 10,
    imageUrl: 'https://cdn.myanimelist.net/images/anime/1223/96541.jpg',
    reveiw:
      'Great story, great characters, honestly best anime of all time no questions asked',
    startDate: new Date(2013, 8, 11),
    endDate: new Date(2013, 8, 13),
    episodeTotal: 64,
    currentEp: 64,
    language: 'english',
  },
  flcl: {
    title: 'FLCL',
    isFav: true,
    rating: 7,
    imageUrl: 'https://cdn.myanimelist.net/images/anime/4/24987.jpg',
    reveiw: '',
    startDate: new Date(2015, 6, 12),
    endDate: new Date(2015, 6, 13),
    episodeTotal: 6,
    currentEp: 6,
    language: 'english',
  },
  progressive: {
    title: 'FLCL Progressive',
    isFav: false,
    rating: 4,
    imageUrl: 'https://cdn.myanimelist.net/images/anime/1736/91291.jpg',
    reveiw: '',
    startDate: new Date(2018, 5, 3),
    endDate: new Date(2018, 6, 7),
    episodeTotal: 6,
    currentEp: 6,
    language: 'english',
  },
  alternative: {
    title: 'FLCL Alternative',
    isFav: false,
    rating: 5,
    imageUrl: 'https://cdn.myanimelist.net/images/anime/1494/93701.jpg',
    reveiw: '',
    startDate: new Date(2018, 8, 7),
    endDate: new Date(2019, 0, 17),
    episodeTotal: 6,
    currentEp: 6,
    language: 'english',
  },
  kingsGame: {
    title: "King's Game",
    episodeTotal: 13,
    currentEp: 2,
    language: 'english',
  },
};
